services:
  coordinator:
    image: coordinator:v1.0
    build:
      context: ../
      dockerfile: docker/coordinator/Dockerfile
    ports:
      - 9090:9090
  worker:
    image: worker:v1.0
    platform: linux/amd64
    build:
      context: ../
      dockerfile: docker/worker/Dockerfile
    ports:
      - 9000:9000/udp
    depends_on:
      - coordinator